### ISSUE TITLE
替换llm

### ISSUE THREAD

**Issue by dorbodwolf** [aiwaves-cn/agents#100]
请问下替换自己本地部署的llm的api，这块有没有文档指引

**Comment by jianghuyihei** [comment]
目前没有，之后会进行补充，目前来说你可以看看src/agents/llm/base_llm里的初始化方法，你可以修改成自己的llm，只要保证方法接口是get_response就可以

**Comment by dorbodwolf** [comment]
> 目前没有，之后会进行补充，目前来说你可以看看src/agents/llm/base_llm里的初始化方法，你可以修改成自己的llm，只要保证方法接口是get_response就可以

okay，我在尝试实现
