### ISSUE TITLE
Support more search engines and more data in the `WebSearchComponent`

### ISSUE THREAD

**Issue by ilyazub** [aiwaves-cn/agents#106]
Currently the `WebSearchComponent` supports Google and Bing organic search results.

https://github.com/aiwaves-cn/agents/blob/b4ec7043afcd940ce03508fc2509a4e0cb6c9db8/src/agents/Component/ToolComponent.py#L173

More data can be obtained in a similar way to Langchain (ref: https://github.com/langchain-ai/langchain/blob/48a04aed7539f47a2a12fbe8b863a7813814ff86/libs/langchain/langchain/utilities/serpapi.py#L128-L215). 

We'd be happy to integrate SerpApi into aiwaves-agents.

What do you think about supporting more data from Google, Bing, and other search engines results pages?

**Comment by MichaelZhouwang** [comment]
I think it is a great point!  It would be great it you can help integrate SerpAPI into the framework! Your help is very much appreciated! Please raise a PR when you finish it! Thanks a lot!
