### ISSUE TITLE
pip intall ai-agents ERROR!

### ISSUE THREAD

**Issue by Jackie-shi** [aiwaves-cn/agents#120]
When I use the `pip intall ai-agents`, the install returns a error message:

```
ERROR: Cannot install ai-agents==0.0.1, ai-agents==0.0.2 and ai-agents==0.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    ai-agents 0.0.3 depends on langchain==0.0.308
    ai-agents 0.0.2 depends on langchain==0.0.308
    ai-agents 0.0.1 depends on gradio==3.39.0
```

How to solve it?
Thanks!!

**Comment by callanwu** [comment]
you can try ```pip install ai-agents==0.0.3``` to get our latest version or try ```pip install -e``` like https://github.com/aiwaves-cn/agents#option-1--build-from-source

**Comment by Jackie-shi** [comment]
> you can try `pip install ai-agents==0.0.3` to get our latest version or try `pip install -e` like https://github.com/aiwaves-cn/agents#option-1--build-from-source

Thanks, I've installed successfully!
