### ISSUE TITLE
LiteLLM error

### ISSUE THREAD

**Issue by Megic** [aiwaves-cn/agents#121]
![image](https://github.com/aiwaves-cn/agents/assets/1814522/b6b23adb-95d3-438e-800e-c5372b8b5e60)

**Comment by callanwu** [comment]
@ishaan-jaff could you help to fix it?

**Comment by ishaan-jaff** [comment]
taking a look

**Comment by ishaan-jaff** [comment]
@Megic I just tried and it works fine for me 

<img width="1280" alt="Screenshot 2023-10-09 at 6 53 44 AM" src="https://github.com/aiwaves-cn/agents/assets/29436595/a4f0a707-0ae5-4ce4-9e56-228931ab35ac">

are you setting anything in config.json ?

**Comment by callanwu** [comment]
> taking a look

thx a lot

**Comment by ishaan-jaff** [comment]
@Megic what version of litellm are you on ?

**Comment by Megic** [comment]
I use another project to proxy openai 。https://github.com/songquanpeng/one-api 。 
openai module is ok.
