### ISSUE TITLE
Run example ERROR

### ISSUE THREAD

**Issue by Jackie-shi** [aiwaves-cn/agents#122]
I try to run the given example: `python Single_Agent/run_gradio.py --agent Single_Agent/shopping_assistant/config.json`, but it returns the following error message: 

```
server: executing `python Single_Agent/gradio_backend.py --agent Single_Agent/shopping_assistant/config.json` ...
Traceback (most recent call last):
  File "/home/shijiayi/Projects/KI3-LLM/agents/examples/Single_Agent/gradio_backend.py", line 8, in <module>
    from agents.Agent import Agent
ModuleNotFoundError: No module named 'agents.Agent'
```

How to solve it?
Thanks!!

**Comment by jianghuyihei** [comment]
pip install ai-agents first

**Comment by Jackie-shi** [comment]
> pip install ai-agents first

@jianghuyihei I've already installed the ai-agents==0.0.3.

**Comment by jianghuyihei** [comment]
add from .Agent import * in src/agents/__init__.py, we will fix it soon

**Comment by callanwu** [comment]
or you can change 'from agents.XXX import XXX' to 'from XXX import XXX' in run_gradio.py
