### ISSUE TITLE
Connection ERROR

### ISSUE THREAD

**Issue by Jackie-shi** [aiwaves-cn/agents#144]
I've set my own proxy in the config file.
Anyone came into this problem?
`openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:997)")))`

**Comment by jianghuyihei** [comment]
We have also encountered this issue before and there is currently no good solution. You can choose a local embedded model to replace the OpenAI interface.

**Comment by jianghuyihei** [comment]
> I've set my own proxy in the config file. Anyone came into this problem? `openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:997)")))`

Can you take a look at your config settings.If you want to facilitate communication, you can join our WeChat and add my friends

**Comment by Jackie-shi** [comment]
@jianghuyihei I just want to run the example code on my lab server, and the proxy I set is American node. BTW, I've joined the WeChat group, thanks a lot!

**Comment by jianghuyihei** [comment]
> @jianghuyihei I just want to run the example code on my lab server, and the proxy I set is American node. BTW, I've joined the WeChat group, thanks a lot!

You can add my friends, and the group leader is me
