### ISSUE TITLE
ModuleNotFoundError: No module named 'agents.SOP'

### ISSUE THREAD

**Issue by serendipity-t** [aiwaves-cn/agents#161]
cd example
python run.py --agent Multi_Agent/debate/config.json

File "run.py", line 3, in <module>
    from agents.SOP import SOP
ModuleNotFoundError: No module named 'agents.SOP'

**Comment by callanwu** [comment]
hi @serendipity-t , did you pip our latest version package?
you can refer to https://github.com/aiwaves-cn/agents#-installation.
