### ISSUE TITLE
version in requirements

### ISSUE THREAD

**Issue by Aquarius-A** [aiwaves-cn/agents#174]
Can you provide detailed version information in the requirement? As a beginner, I have encountered problems in this area.

**Comment by callanwu** [comment]
Pip the latest version of openai and litellm.

**Comment by Aquarius-A** [comment]
my gradio fastapi and typing_extensions  not match

**Comment by callanwu** [comment]
Try gradio==3.39.0, fastapi==0.103.1, typing_extensions==3.39.0
You need to use our latest codebase and ignore the reported conflict alert, we'll fix them later:)
