### ISSUE TITLE
【解决措施】tensorflow版本问题，module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by TommyTang930** [aiwaves-cn/agents#28]
### 1. 运行环境
系统：Mac OS
Python版本: 3.11
tensorflow版本: 2.13.0
```shell
pip install ai-agents
```
### 2. 按照README.md演示shopping_assistant
```shell
python run.py --agent Single_Agent/shopping_assistant/config.json
```

### 3. 抛出Error
```shell
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

### 4. 解决措施
根据提示，修改脚本文件，路径是: 
```shell
/opt/anaconda3/envs/agents/lib/python3.11/site-packages/agents/scripts/networks.py
```
安装: pip install tensorflow_probability
导入依赖包:
import tensorflow_probability as tfp
将 tfd = tf.contrib.distributions 改为 tfd = tfp.distributions

^_^ 问题解决，可以正常运行Demo了。

**Comment by callanwu** [comment]
Thank you for sharing!

**Comment by wookayin** [comment]
English please

**Comment by Natfan** [comment]
> ### 1. Runtime Environment
> System: Mac OS
> Python version: 3.11
> tensorflow version: 2.13.0
>
> `pip install ai-agents`
> ### 2. Follow README.md to demonstrate shopping_assistant
> python run.py --agent Single_Agent/shopping_assistant/config.json
> ### 3. Throws Error
> AttributeError: module 'tensorflow' has no attribute 'contrib'
> ### 4. Solution
> According to the prompt, modify the script file, the path is:
> 
> /opt/anaconda3/envs/agents/lib/python3.11/site-packages/agents/scripts/networks.py
> Install: pip install tensorflow_probability
> Import dependencies:
> `import tensorflow_probability as tfp`
> Change `tfd = tf.contrib.distributions` to `tfd = tfp.distributions`
> 
> ^_^ Problem solved, Demo can run normally now.

[Provided via [Kagi Translation services](https://translate.kagi.com/github.com/aiwaves-cn/agents/issues/28)]
