### ISSUE TITLE
Software company demo failed

### ISSUE THREAD

**Issue by Germany321** [aiwaves-cn/agents#30]
Your software company demo cannot work.

**Comment by jianghuyihei** [comment]
Thank you for your reminder，we have restarted it. Due to massive traffic, our online demos may suffer from long queue time and unstable issues. You can try copying to your local location, which is quite easy.I hope you have a good experience

**Comment by bmorphism** [comment]
taking a longer view, perhaps a "company" is a rather limiting view given this setting! 👁️ we have a chance to redefine economics, identity, becoming! and we pick... Dilbert? 🤔

**Comment by MichaelZhouwang** [comment]
The demo works now.
