### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cometothed4rkside** [aiwaves-cn/agents#36]
{   "config":{
    "API_KEY" : "xxxxxxx",
    "PROXY" : "",
    "MAX_CHAT_HISTORY" : "1000",
    "User_Names" : "[\"alexander\"]",
    "Embed_Model" : "intfloat/multilingual-e5-large"
},
    "LLM_type": "OpenAI",
    "LLM": {
        "temperature": 0.0,
        "model": "gpt-3.5-turbo-16k-0613",
        "log_path": "logs/god"
    },
    "agents": {
        "Mike": {
            "style":"humorous and professional",
            "roles":{
            "response_state": "customer service personnel"
            }
        },
        "alexander": {
            "style":"cold and unruly",
            "roles":{
            "response_state": "user"
            }
        }
    },
    "root": "response_state",
    "relations": {
        "response_state": {
            "0": "response_state"
        }
    },
    "temperature": 0.6,
    "log_path": "logs",
    "states": {
        "end_state": {
        },
        "response_state": {
            "controller": {
                "controller_type": "order"
            },
            "begin_role": "customer service personnel",
            "begin_query": "hello, could i can help you?",
            "environment_prompt": "",
            "roles": [
                "customer service personnel",
                "user"
            ],
            "LLM_type": "OpenAI",
            "LLM": {
                "temperature": 1.0,
                "model": "gpt-3.5-turbo-16k-0613",
                "log_path": "logs/customer_service"
            },
            "agent_states": {
                "customer service personnel": {
                    "style": {
                        "role": "customer service personnel"
                    },
                    "task": {
                        "task": "answer user's question"
                    },
                    "rule": {
                        "rule": "Keep your response as concise as possible."
                    },
                    "KnowledgeBaseComponent": {
                        "top_k": 1,
                        "type": "QA",
                        "knowledge_path": "Single_Agent/customer_service/easy_question.json"
                    }
                },
                "user": {
                }
            }
        }
    }
}

C:\Users\xxxxx\Desktop\agents\examples>python run.py --agent Single_Agent/customer_service/customer_knowledge.json
path Single_Agent/customer_service/easy_question.json
Mike(customer service personnel):hello, could i can help you?
alexander:selam
0.7510939240455627
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\agents\examples\run.py", line 44, in <module>
    run(agents,sop,environment)
  File "C:\Users\xxxx\Desktop\agents\examples\run.py", line 35, in run
    memory = action.process()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\Action\base_action.py", line 25, in process
    for res in response:
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\LLM\base_LLM.py", line 39, in get_stream
    save_logs(log_path, messages, ans)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\agents\utils.py", line 127, in save_logs
    with open(log_file, "w", encoding="utf-8") as f:
OSError: [Errno 22] Invalid argument: 'logs/Mike\\2023-09-1801:15:51.json'

**Comment by jianghuyihei** [comment]
> **How to Fix**
> 
> 1. First, locate and open the **agents\utils.py** file within your project directory.
> 2. Use a text editor (such as Notepad++ or Visual Studio Code) to make the necessary changes.
> 3. Next, locate line 124. This line represents a code block used to create the name of the log file.
> 4. Now, you can correct this line as follows:
> 
> ```python
> log_file = os.path.join(
>     log_path,
>     datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".json"
> )
> ```
> 
> This change will correctly format the name of the log file with the specified date and time format.

Thank you for your reminder, valuable feedback

**Comment by jianghuyihei** [comment]
> **How to Fix**
> 
> 1. First, locate and open the **agents\utils.py** file within your project directory.
> 2. Use a text editor (such as Notepad++ or Visual Studio Code) to make the necessary changes.
> 3. Next, locate line 124. This line represents a code block used to create the name of the log file.
> 4. Now, you can correct this line as follows:
> 
> ```python
> log_file = os.path.join(
>     log_path,
>     datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".json"
> )
> ```
> 
> This change will correctly format the name of the log file with the specified date and time format.

Thank you for your reminder, valuable feedback

**Comment by MichaelZhouwang** [comment]
fixed and updated
