### ISSUE TITLE
Collaborative Opportunity: Sharing your Gradio demo via HuggingFace Hub

### ISSUE THREAD

**Issue by yvrjsharma** [aiwaves-cn/agents#66]
Hi 🤗  !
Very cool work with Gradio demos linked on the Readme! It would be nice to host these awesome demos on the [Hugging Face Hub](https://huggingface.co/spaces) !
Some of the benefits of sharing your models through the Hub would be:

- A wider reach of your work to the ecosystem
- Seamless integration with popular libraries and frameworks, enhancing usability
- Real-time feedback and collaboration opportunities with a global community of researchers and developers

This is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process in case you're interested. 😊 This is our docs on [Community GPU Grants](https://huggingface.co/docs/hub/spaces-gpus#community-gpu-grants).

**Comment by callanwu** [comment]
Thank you for the invitation! 
We are now encountering a problem in the deployment process, if multiple users use it at the same time, sometimes it will be misplaced or queue for a long time, how should we solve this problem?

**Comment by yvrjsharma** [comment]
Sure, is this problem on the Spaces-hosted demos or the local ones?

**Comment by callanwu** [comment]
Both seem to run into this problem, and one of our Spaces-hosted demos is here: https://huggingface.co/spaces/AIWaves/Software_Company.

**Comment by yvrjsharma** [comment]
I am unable to use this demo. I can see an error in the logs as - 
> assert self.FIRST_RECIEVE_FROM_CLIENT, "Please make sure you have executed `self.first_recieve_from_client()` manually."
AssertionError: Please make sure you have executed `self.first_recieve_from_client()` manually.

Is this the error you were talking about? I am not sure if this is a Gradio or Spaces issue. You might want to double-check that there's no logic elsewhere in your code that's setting FIRST_RECIEVE_FROM_CLIENT back to False prematurely.

**Comment by callanwu** [comment]
Yes. We'll check this problem, we think that the issue arises from the simultaneous use by multiple users. And thank you again!
