### ISSUE TITLE
Running the software company demo locally raises error

### ISSUE THREAD

**Issue by mpaepper** [aiwaves-cn/agents#71]
Running the Muti_agent/software_company example locally, I get:

```
Traceback (most recent call last):
  File "/var/www/html/agents/examples/run.py", line 44, in <module>
    run(agents,sop,environment)
  File "/var/www/html/agents/examples/run.py", line 35, in run
    memory = action.process()
  File "/var/www/html/agents/examples/../src/agents/Action/base_action.py", line 39, in process
    title = extract(all,"title")
NameError: name 'extract' is not defined
```

**Comment by jianghuyihei** [comment]
> Running the Muti_agent/software_company example locally, I get:
> 
> ```
> Traceback (most recent call last):
>   File "/var/www/html/agents/examples/run.py", line 44, in <module>
>     run(agents,sop,environment)
>   File "/var/www/html/agents/examples/run.py", line 35, in run
>     memory = action.process()
>   File "/var/www/html/agents/examples/../src/agents/Action/base_action.py", line 39, in process
>     title = extract(all,"title")
> NameError: name 'extract' is not defined
> ```

Add from utils import extract
