### ISSUE TITLE
Error running locally ：RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by yakami129** [aiwaves-cn/agents#74]
Config:
```
{
  "config": {
    "API_KEY": "sk-xxxx",
    "PROXY": "http://127.0.0.1:23457",
    "API_BASE": "",
    "MAX_CHAT_HISTORY": "5",
    "MIN_CATEGORY_SIM": "0.7",
    "FETSIZE": "3",
    "User_Names": "[\"Mike\"]",
    "SHOPPING_SEARCH": "Your search url"
  },
  "LLM_type": "OpenAI",
  "LLM": {
    "temperature": 0.3,
    "model": "gpt-3.5-turbo-16k-0613",
    "log_path": "logs/god"
  },
  "root": "shopping_state",
  "relations": {
    "shopping_state": {
      "0": "shopping_state",
      "1": "end_state"
    }
  },
  "agents": {
    "Jonh": {
      "style": "humorous",
      "roles": {
        "shopping_state": "Shopping assistant"
      }
    },
    "Mike": {
      "style": "indifferent",
      "roles": {
        "shopping_state": "customer"
      }
    }
  },
  "states": {
    "end_state": {},
    "shopping_state": {
      "roles": [
        "Shopping assistant",
        "customer"
      ],
      "controller": {
        "controller_type": "order",
        "judge_system_prompt": "",
        "judge_last_prompt": "response<end>0<end>",
        "judge_extract_words": "end",
        "call_system_prompt": "",
        "call_last_prompt": "",
        "call_extract_words": "end"
      },
      "environment_prompt": "The current scenario is an AI shopping guide answering customers' questions and recommending corresponding products based on the user's needs to induce users to buy. The main roles are: shopping_assistant (Jonh) is responsible for answering users’ questions, and customers (Mike) come to consult shopping opinions.",
      "begin_role": "Shopping assistant",
      "begin_query": "Welcome to the store, is there anything you want to buy?",
      "agent_states": {
        "Shopping assistant": {
          "style": {
            "role": "Shopping assistant",
            "style": "humorous"
          },
          "task": {
            "task": "Guide users to purchase goods"
          },
          "rule": {
            "rule": "Your language should be as concise as possible, without too much nonsense. You have to repeatedly guide customers to purchase goods"
          },
          "CategoryRequirementsComponent": {
            "information_path": [
              "Single_Agent/shopping_assistant/bb_info.json",
              "Single_Agent/shopping_assistant/toy_info.json"
            ]
          }
        },
        "customer": {
          "style": {
            "role": "customer"
          },
          "task": {
            "task": "Make things difficult for the shopping guide and ask him to provide as much product information as possible"
          },
          "rule": {
            "rule": "Your language should be as concise as possible, without too much nonsense. You cannot ask questions repeatedly. You need to ask different aspects each time, and you can also ask questions reasonably. You can choose not to shop, but you must ask for as much information as possible. You need to constantly ask for different aspects of product information and follow up reasonably. Remember, your tone needs to be cold and your style needs to be tricky"
          }
        }
      }
    }
  }
}
```

Command：
```
 python run.py --agent Single_Agent/shopping_assistant/config.json
```

Error Log:
```
Jonh(Shopping assistant):Welcome to the store, is there anything you want to buy?
Mike: hell
Jonh(Shopping assistant):Hey Mike, welcome to the store! How can I assist you today? Is there something specific you're looking to buy?
Mike: Buy toys
Traceback (most recent call last):
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/run.py", line 44, in <module>
    run(agents,sop,environment)
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/run.py", line 34, in run
    action = current_agent.step(current_state,user_input)   #component_dict = current_state[self.role[current_node.name]]   current_agent.compile(component_dict)
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 131, in step
    response,res_dict = self.act()
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 153, in act
    system_prompt, last_prompt, res_dict = self.compile()
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 218, in compile
    response = component.func(self)
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Component/ExtraComponent.py", line 89, in func
    topk_result = matching_category(
  File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/utils.py", line 357, in matching_category
    top_k_cat = torch.topk(total_scores, k=top_k)
RuntimeError: selected index k out of range
```

**Comment by jianghuyihei** [comment]
> Config:
> 
> ```
> {
>   "config": {
>     "API_KEY": "sk-xxxx",
>     "PROXY": "http://127.0.0.1:23457",
>     "API_BASE": "",
>     "MAX_CHAT_HISTORY": "5",
>     "MIN_CATEGORY_SIM": "0.7",
>     "FETSIZE": "3",
>     "User_Names": "[\"Mike\"]",
>     "SHOPPING_SEARCH": "Your search url"
>   },
>   "LLM_type": "OpenAI",
>   "LLM": {
>     "temperature": 0.3,
>     "model": "gpt-3.5-turbo-16k-0613",
>     "log_path": "logs/god"
>   },
>   "root": "shopping_state",
>   "relations": {
>     "shopping_state": {
>       "0": "shopping_state",
>       "1": "end_state"
>     }
>   },
>   "agents": {
>     "Jonh": {
>       "style": "humorous",
>       "roles": {
>         "shopping_state": "Shopping assistant"
>       }
>     },
>     "Mike": {
>       "style": "indifferent",
>       "roles": {
>         "shopping_state": "customer"
>       }
>     }
>   },
>   "states": {
>     "end_state": {},
>     "shopping_state": {
>       "roles": [
>         "Shopping assistant",
>         "customer"
>       ],
>       "controller": {
>         "controller_type": "order",
>         "judge_system_prompt": "",
>         "judge_last_prompt": "response<end>0<end>",
>         "judge_extract_words": "end",
>         "call_system_prompt": "",
>         "call_last_prompt": "",
>         "call_extract_words": "end"
>       },
>       "environment_prompt": "The current scenario is an AI shopping guide answering customers' questions and recommending corresponding products based on the user's needs to induce users to buy. The main roles are: shopping_assistant (Jonh) is responsible for answering users’ questions, and customers (Mike) come to consult shopping opinions.",
>       "begin_role": "Shopping assistant",
>       "begin_query": "Welcome to the store, is there anything you want to buy?",
>       "agent_states": {
>         "Shopping assistant": {
>           "style": {
>             "role": "Shopping assistant",
>             "style": "humorous"
>           },
>           "task": {
>             "task": "Guide users to purchase goods"
>           },
>           "rule": {
>             "rule": "Your language should be as concise as possible, without too much nonsense. You have to repeatedly guide customers to purchase goods"
>           },
>           "CategoryRequirementsComponent": {
>             "information_path": [
>               "Single_Agent/shopping_assistant/bb_info.json",
>               "Single_Agent/shopping_assistant/toy_info.json"
>             ]
>           }
>         },
>         "customer": {
>           "style": {
>             "role": "customer"
>           },
>           "task": {
>             "task": "Make things difficult for the shopping guide and ask him to provide as much product information as possible"
>           },
>           "rule": {
>             "rule": "Your language should be as concise as possible, without too much nonsense. You cannot ask questions repeatedly. You need to ask different aspects each time, and you can also ask questions reasonably. You can choose not to shop, but you must ask for as much information as possible. You need to constantly ask for different aspects of product information and follow up reasonably. Remember, your tone needs to be cold and your style needs to be tricky"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> Command：
> 
> ```
>  python run.py --agent Single_Agent/shopping_assistant/config.json
> ```
> 
> Error Log:
> 
> ```
> Jonh(Shopping assistant):Welcome to the store, is there anything you want to buy?
> Mike: hell
> Jonh(Shopping assistant):Hey Mike, welcome to the store! How can I assist you today? Is there something specific you're looking to buy?
> Mike: Buy toys
> Traceback (most recent call last):
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/run.py", line 44, in <module>
>     run(agents,sop,environment)
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/run.py", line 34, in run
>     action = current_agent.step(current_state,user_input)   #component_dict = current_state[self.role[current_node.name]]   current_agent.compile(component_dict)
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 131, in step
>     response,res_dict = self.act()
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 153, in act
>     system_prompt, last_prompt, res_dict = self.compile()
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Agent/Agent.py", line 218, in compile
>     response = component.func(self)
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/Component/ExtraComponent.py", line 89, in func
>     topk_result = matching_category(
>   File "/Users/zhangyajun/Documents/CodeWorkSpace/skyjun/agents/examples/../src/agents/utils.py", line 357, in matching_category
>     top_k_cat = torch.topk(total_scores, k=top_k)
> RuntimeError: selected index k out of range
> ```

Due to the removal of our partner company's search engine, we currently do not support shopping assistant. Please try another demo and we will try changing the search engine later. Sorry!

**Comment by yakami129** [comment]
Thank you.
