### ISSUE TITLE
Details on Proxy and API Base

### ISSUE THREAD

**Issue by ranavijay07** [aiwaves-cn/agents#78]
Hi, I am having trouble when running it in my local environment. What is proxy and api base that needs to be added in the config file? Where can i generate that information?

**Comment by callanwu** [comment]
if you can communicate with openai directly, you can remove them from config.

**Comment by ranavijay07** [comment]
When i run without those options, I still get the below error, Can you help me with details on how to set up Proxy?

File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027606CFA810>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by foreverpiano** [comment]
openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by callanwu** [comment]
> openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

Because we use 'text-embedding-ada-002' from OpenAI as the default embedding model, you may encounter rate limit issues. You can change the embedding model by "config" key. You can check the config.json like this:
https://github.com/aiwaves-cn/agents/blob/ce96b9df8744370388d8b74a596afdae8d4f3f38/examples/Single_Agent/oculist_agent/config.json#L10
The 'Embed_Model' parameter can be set to any embedding model from the following list on Hugging Face's website: 
https://huggingface.co/models?pipeline_tag=sentence-similarity&sort=trending

**Comment by jianghuyihei** [comment]
> openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

And the knowledge base of the demos we provide is pre encoded using 'text embedding ada-002'. If you change the embedding model, you can reuse the new embedding model to build the knowledge base yourself. For more information, please use to the function process_document in src/utils.

**Comment by Lottie641** [comment]
> "Embed_Model": "intfloat/multilingual-e5-large"

Hi, I have the same error after removing Proxy and API base. Does your error have been solved?

**Comment by greatel** [comment]
> > openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
> 
> Because we use 'text-embedding-ada-002' from OpenAI as the default embedding model, you may encounter rate limit issues. You can change the embedding model by "config" key. You can check the config.json like this:
> 
> https://github.com/aiwaves-cn/agents/blob/ce96b9df8744370388d8b74a596afdae8d4f3f38/examples/Single_Agent/oculist_agent/config.json#L10
> 
> 
> The 'Embed_Model' parameter can be set to any embedding model from the following list on Hugging Face's website:
> https://huggingface.co/models?pipeline_tag=sentence-similarity&sort=trending

Thank, @callanwu ! But I have tried the approach you provided. it still show the similar error as below (which seems to be still related to proxy settings). For the users in the US, we don't need a proxy to visit openai, is there anyway we can get around it? Thanks.

openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2bdf7f250>: Failed to establish a new connection: [Errno 61] Connection refused')))

**Comment by jianghuyihei** [comment]
> > > openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
> > 
> > 
> > Because we use 'text-embedding-ada-002' from OpenAI as the default embedding model, you may encounter rate limit issues. You can change the embedding model by "config" key. You can check the config.json like this:
> > https://github.com/aiwaves-cn/agents/blob/ce96b9df8744370388d8b74a596afdae8d4f3f38/examples/Single_Agent/oculist_agent/config.json#L10
> > 
> > The 'Embed_Model' parameter can be set to any embedding model from the following list on Hugging Face's website:
> > https://huggingface.co/models?pipeline_tag=sentence-similarity&sort=trending
> 
> Thank, @callanwu ! But I have tried the approach you provided. it still show the similar error as below (which seems to be still related to proxy settings). For the users in the US, we don't need a proxy to visit openai, is there anyway we can get around it? Thanks.
> 
> openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2bdf7f250>: Failed to establish a new connection: [Errno 61] Connection refused')))

Because you did not set a global proxy, our proxy settings are only for openai,not for hugging face.
