### ISSUE TITLE
Unable to run this locally

### ISSUE THREAD

**Issue by foreverpiano** [aiwaves-cn/agents#79]
config
```
{
  "config": {
    "API_KEY": "sk-",
    "PROXY": "http://127.0.0.1:7890",
    "API_BASE": "",
    "MAX_CHAT_HISTORY": "5",
    "MIN_CATEGORY_SIM": "0.7",
    "FETSIZE": "3",
    "User_Names": "[\"Mike\"]",
    "SHOPPING_SEARCH": "Your search url"
  },
  "LLM_type": "OpenAI",
  "LLM": {
    "temperature": 0.3,
    "model": "gpt-3.5-turbo-16k-0613",
    "log_path": "logs/god"
  },
  "root": "shopping_state",
  "relations": {
    "shopping_state": {
      "0": "shopping_state",
      "1": "end_state"
    }
  },
  "agents": {
    "Jonh": {
      "style": "humorous",
      "roles": {
        "shopping_state": "Shopping assistant"
      }
    },
    "Mike": {
      "style": "indifferent",
      "roles": {
        "shopping_state": "customer"
      }
    }
  },
  "states": {
    "end_state": {},
    "shopping_state": {
      "roles": [
        "Shopping assistant",
        "customer"
      ],
      "controller": {
        "controller_type": "order",
        "judge_system_prompt": "",
        "judge_last_prompt": "response<end>0<end>",
        "judge_extract_words": "end",
        "call_system_prompt": "",
        "call_last_prompt": "",
        "call_extract_words": "end"
      },
      "environment_prompt": "The current scenario is an AI shopping guide answering customers' questions and recommending corresponding products based on the user's needs to induce users to buy. The main roles are: shopping_assistant (Jonh) is responsible for answering users’ questions, and customers (Mike) come to consult shopping opinions.",
      "begin_role": "Shopping assistant",
      "begin_query": "Welcome to the store, is there anything you want to buy?",
      "agent_states": {
        "Shopping assistant": {
          "style": {
            "role": "Shopping assistant",
            "style": "humorous"
          },
          "task": {
            "task": "Guide users to purchase goods"
          },
          "rule": {
            "rule": "Your language should be as concise as possible, without too much nonsense. You have to repeatedly guide customers to purchase goods"
          },
          "CategoryRequirementsComponent": {
            "information_path": [
              "Single_Agent/shopping_assistant/bb_info.json",
              "Single_Agent/shopping_assistant/toy_info.json"
            ]
          }
        },
        "customer": {
          "style": {
            "role": "customer"
          },
          "task": {
            "task": "Make things difficult for the shopping guide and ask him to provide as much product information as possible"
          },
          "rule": {
            "rule": "Your language should be as concise as possible, without too much nonsense. You cannot ask questions repeatedly. You need to ask different aspects each time, and you can also ask questions reasonably. You can choose not to shop, but you must ask for as much information as possible. You need to constantly ask for different aspects of product information and follow up reasonably. Remember, your tone needs to be cold and your style needs to be tricky"
          }
        }
      }
    }
  }
}
```
command & error

```
python run.py --agent Single_Agent/shopping_assistant/config.json
Jonh(Shopping assistant):Welcome to the store, is there anything you want to buy?
Mike:candy
Traceback (most recent call last):
  File "/workspace/dhl/agents/examples/run.py", line 44, in <module>
    run(agents,sop,environment)
  File "/workspace/dhl/agents/examples/run.py", line 34, in run
    action = current_agent.step(current_state,user_input)   #component_dict = current_state[self.role[current_node.name]]   current_agent.compile(component_dict)
  File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 131, in step
    response,res_dict = self.act()
  File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 153, in act
    system_prompt, last_prompt, res_dict = self.compile()
  File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 218, in compile
    response = component.func(self)
  File "/workspace/dhl/agents/examples/../src/agents/Component/ExtraComponent.py", line 89, in func
    topk_result = matching_category(
  File "/workspace/dhl/agents/examples/../src/agents/utils.py", line 345, in matching_category
    input_embeder = get_embedding(inputtext)
  File "/workspace/dhl/agents/examples/../src/agents/utils.py", line 53, in get_embedding
    embed = embedding_model.create(
  File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method
```

**Comment by callanwu** [comment]
maybe https://github.com/aiwaves-cn/agents/issues/78#issuecomment-1730600361 can help you

**Comment by jianghuyihei** [comment]
> config
> 
> ```
> {
>   "config": {
>     "API_KEY": "sk-",
>     "PROXY": "http://127.0.0.1:7890",
>     "API_BASE": "",
>     "MAX_CHAT_HISTORY": "5",
>     "MIN_CATEGORY_SIM": "0.7",
>     "FETSIZE": "3",
>     "User_Names": "[\"Mike\"]",
>     "SHOPPING_SEARCH": "Your search url"
>   },
>   "LLM_type": "OpenAI",
>   "LLM": {
>     "temperature": 0.3,
>     "model": "gpt-3.5-turbo-16k-0613",
>     "log_path": "logs/god"
>   },
>   "root": "shopping_state",
>   "relations": {
>     "shopping_state": {
>       "0": "shopping_state",
>       "1": "end_state"
>     }
>   },
>   "agents": {
>     "Jonh": {
>       "style": "humorous",
>       "roles": {
>         "shopping_state": "Shopping assistant"
>       }
>     },
>     "Mike": {
>       "style": "indifferent",
>       "roles": {
>         "shopping_state": "customer"
>       }
>     }
>   },
>   "states": {
>     "end_state": {},
>     "shopping_state": {
>       "roles": [
>         "Shopping assistant",
>         "customer"
>       ],
>       "controller": {
>         "controller_type": "order",
>         "judge_system_prompt": "",
>         "judge_last_prompt": "response<end>0<end>",
>         "judge_extract_words": "end",
>         "call_system_prompt": "",
>         "call_last_prompt": "",
>         "call_extract_words": "end"
>       },
>       "environment_prompt": "The current scenario is an AI shopping guide answering customers' questions and recommending corresponding products based on the user's needs to induce users to buy. The main roles are: shopping_assistant (Jonh) is responsible for answering users’ questions, and customers (Mike) come to consult shopping opinions.",
>       "begin_role": "Shopping assistant",
>       "begin_query": "Welcome to the store, is there anything you want to buy?",
>       "agent_states": {
>         "Shopping assistant": {
>           "style": {
>             "role": "Shopping assistant",
>             "style": "humorous"
>           },
>           "task": {
>             "task": "Guide users to purchase goods"
>           },
>           "rule": {
>             "rule": "Your language should be as concise as possible, without too much nonsense. You have to repeatedly guide customers to purchase goods"
>           },
>           "CategoryRequirementsComponent": {
>             "information_path": [
>               "Single_Agent/shopping_assistant/bb_info.json",
>               "Single_Agent/shopping_assistant/toy_info.json"
>             ]
>           }
>         },
>         "customer": {
>           "style": {
>             "role": "customer"
>           },
>           "task": {
>             "task": "Make things difficult for the shopping guide and ask him to provide as much product information as possible"
>           },
>           "rule": {
>             "rule": "Your language should be as concise as possible, without too much nonsense. You cannot ask questions repeatedly. You need to ask different aspects each time, and you can also ask questions reasonably. You can choose not to shop, but you must ask for as much information as possible. You need to constantly ask for different aspects of product information and follow up reasonably. Remember, your tone needs to be cold and your style needs to be tricky"
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> command & error
> 
> ```
> python run.py --agent Single_Agent/shopping_assistant/config.json
> Jonh(Shopping assistant):Welcome to the store, is there anything you want to buy?
> Mike:candy
> Traceback (most recent call last):
>   File "/workspace/dhl/agents/examples/run.py", line 44, in <module>
>     run(agents,sop,environment)
>   File "/workspace/dhl/agents/examples/run.py", line 34, in run
>     action = current_agent.step(current_state,user_input)   #component_dict = current_state[self.role[current_node.name]]   current_agent.compile(component_dict)
>   File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 131, in step
>     response,res_dict = self.act()
>   File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 153, in act
>     system_prompt, last_prompt, res_dict = self.compile()
>   File "/workspace/dhl/agents/examples/../src/agents/Agent/Agent.py", line 218, in compile
>     response = component.func(self)
>   File "/workspace/dhl/agents/examples/../src/agents/Component/ExtraComponent.py", line 89, in func
>     topk_result = matching_category(
>   File "/workspace/dhl/agents/examples/../src/agents/utils.py", line 345, in matching_category
>     input_embeder = get_embedding(inputtext)
>   File "/workspace/dhl/agents/examples/../src/agents/utils.py", line 53, in get_embedding
>     embed = embedding_model.create(
>   File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
>     response = super().create(*args, **kwargs)
>   File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
>     response, _, api_key = requestor.request(
>   File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
>     resp, got_stream = self._interpret_response(result, stream)
>   File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
>     self._interpret_response_line(
>   File "/workspace/dhl/conda/envs/ag/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
>     raise self.handle_error_response(
> openai.error.RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-lzTj3mnzjnM5lxYLwxprz3di on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method
> ```
Due to changing the search engine of our partner company, the shopping assistant is currently in a unusable state. You can try our other demo.
