### ISSUE TITLE
Can PROXY and API_BASE not be set?

### ISSUE THREAD

**Issue by houjibofa2050** [aiwaves-cn/agents#87]
PROXY  =  #Your proxy
    API_BASE  = # Your api_base
What do the two values PROXY and API_BASE mean?

**Comment by callanwu** [comment]
these two variables correspond to the openai's interface. if you don't need them, you can set them to null("PROXY": "","API_BASE": "") or remove them in config.

**Comment by Lottie641** [comment]
After removing the Proxy and API_base, I encounter the following error:
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000290CE44FF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
I'm in US, do I need to set the Proxy and API_base?

**Comment by greatel** [comment]
> After removing the Proxy and API_base, I encounter the following error: openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000290CE44FF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) I'm in US, do I need to set the Proxy and API_base?

The same problem here. The webui suggest using something http://127.0.0.1:7890, but I have tried, it doesn't work.

**Comment by ShaneYuTH** [comment]
After removing the Proxy and API_base, I encounter the following error, different from above, I'm in US as well:Traceback (most recent call last):
  File "/.../agents_pg/agents/examples/run.py", line 44, in <module>
    run(agents,sop,environment)
  File "/.../agents_pg/agents/examples/run.py", line 36, in run
    environment.update_memory(memory,current_state)
  File "/.../agents_pg/agents/examples/../src/agents/Environment/base_environment.py", line 90, in update_memory
    current_embedding = get_embedding(memory.content)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../agents_pg/agents/examples/../src/agents/utils.py", line 48, in get_embedding
    assert "http:" in os.environ["PROXY"] or "socks" in os.environ["PROXY"],"PROXY error,PROXY must be http or socks"
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: PROXY error,PROXY must be http or socks

**Comment by jianghuyihei** [comment]
Thank you for your reminder. We have fixed this bug
